version: '3'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/rn_test
    depends_on:
    - db
  db:
    image: postgres
    volumes:
     - ./tmp/db:/var/lib/postgresql/data